name: neocolor
description: Color definition, manipulation, conversion, and comparison in fluent Dart.
version: 0.1.0
homepage: https://github.com/neo-dart/neocolor

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  coverage: ^1.5.0
  neodart: ^0.1.1
  test: ^1.21.4
